name: Gradle Build

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
      - name: Build with Gradle
        run: gradle build
      - name: Deploy
        run: gradle publish
        env:
          USERNAME: g0ddest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
